### ISSUE TITLE
用npm包引入的方式使用，之前有引入jquery1.12.4就报错了

### ISSUE THREAD

**Issue by HeGangSZ** [tencentyun/cos-js-sdk-v4#13]
用npm包引入的方式使用，之前有引入jquery1.12.4，在业务逻辑和jquery之间有使用jquery的代码，结果就报错了
<img width="692" alt="111" src="https://user-images.githubusercontent.com/15183304/27531373-e8cea30a-5a8e-11e7-9108-e619cf51916a.png">
<img width="549" alt="222" src="https://user-images.githubusercontent.com/15183304/27531394-033f3ace-5a8f-11e7-86b3-67a681f94ef6.png">
<img width="677" alt="333" src="https://user-images.githubusercontent.com/15183304/27531380-f1d40350-5a8e-11e7-9f53-8e4469e3bc98.png">

**Comment by carsonxu** [comment]
好的，近期修复这个问题。

**Comment by carsonxu** [comment]
fixed
