### ISSUE TITLE
iphone5s跟iphone6上传普通文件失败的问题

### ISSUE THREAD

**Issue by Toland12** [tencentyun/cos-js-sdk-v4#15]
网页端跟其他设备目前没有问题
iphone5s跟iphone6微信自带浏览器上传普通文件，会执行errorCallBack函数
`var errorCallBack = function (result) {
        alert(JSON.stringify(result));
 };`

打印效果为：
![image](https://user-images.githubusercontent.com/4065843/27668491-f4e5f0c2-5cb3-11e7-8218-f4992b5c9435.png)

**Comment by Toland12** [comment]
iphone自带的Safari也不可以:(

**Comment by carsonxu** [comment]
应该是CORS是配置问题，safari 请求可能会带有 Access-Control-Allow-Headers:origin,accept,content-type
需要在CORS规则里面配置这几个AllowHeaders

**Comment by carsonxu** [comment]
昨天有看到你这个问题，是否已解决？

**Comment by Toland12** [comment]
是的，已经解决了，非常感谢。
请收下我的膝盖orz
