### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_1_cos_js_sdk_v4__.CosCloud is not a constructor

### ISSUE THREAD

**Issue by aresa7796** [tencentyun/cos-js-sdk-v4#17]
我使用Angular4和cos-js-sdk-v4的1.1.1版本，网页中引入了jquery，但是在初始化CosCloud时，报错。 这是错误信息：
![qq 20170716213125](https://user-images.githubusercontent.com/5482599/28248164-7cf4b16c-6a72-11e7-9a66-10363433f43a.png)

**Comment by carsonxu** [comment]
感谢反馈，我今晚处理下这个问题

**Comment by carsonxu** [comment]
已更新版本到 1.1.2 ，验证看看是否还有问题。@aresa7796
