### ISSUE TITLE
iphone6s 系统版本10.0.2中使用js SDK时SDK抛出错误

### ISSUE THREAD

**Issue by GangCode** [tencentyun/cos-js-sdk-v4#20]
最近开发微信公众号，使用html5开发，有文件上传的功能中使用了腾讯云提供的js cos-js-sdk-v4类库，上传图片到腾讯云盘，经过多种机型的测试发现，在iphone6s 版本号为10.0.2的系统中都无法上传图片，上传图片的API cos.uploadFile(successCallBack, errorCallBack, progressCallBack, bucket, folder + fileName, file, 0, taskReady) 调用上传方法后，直接进入错误回调 errorCallBack，弹出的错误回调result.responseText内容为空字符串。在多台iphone6s上都是出现同样的问题，将iphone6s的系统升级到最新后，上传文件正常。请问这是SDK的兼容性问题吗？

**Comment by carsonxu** [comment]
这里可能是因为跨域规则没配置好：
ios 的浏览器发起请求会带有这样的头部，```Access-Control-Request-Header: accept,content-type```
你试试给 bucket 的 CORS 规则里配置 AllowHeader：
```
origin
accept
content-type
authorization
```

**Comment by GangCode** [comment]
问题已解决，非常感谢！
