### ISSUE TITLE
请问下，sha1值只能在文件大小大于20M才会就算么？ 我想任何文件都计算sha1值，怎么改？

### ISSUE THREAD

**Issue by WiFiUncle** [tencentyun/cos-js-sdk-v4#21]
问题：
1.  sha1是在文件上传之前就计算好的么(会阻塞上传么？ sha没算好，就不上传)？
2.  cos-js-sdk-v4 这个文件有相关文档么？
有空帮忙解答，万分感谢！

**Comment by carsonxu** [comment]
1. 获取上传 session 的时候需要传每个分片的 sha 值，会阻塞上传。
如果想任何文件都计算 sha1 可以直接调用 sliceUploadFile 接口
2. 有文档：https://cloud.tencent.com/document/product/436/8095
