### ISSUE TITLE
ios9上传图片，无法识别

### ISSUE THREAD

**Issue by wang1986573** [tencentyun/cos-js-sdk-v4#23]
ios9上传图片，无法识别

**Comment by carsonxu** [comment]
是包什么错误？有可能是 CORS 配置不完善，试试给 CORS 的 AllowHeaders 配置 *。
ios浏览器发请求的时候可能会带有 Access-Control-Request-Headers: accept,content-type

**Comment by wang1986573** [comment]
报跨域的错误

具体怎么配置 allowheaders？

**Comment by carsonxu** [comment]
https://console.qcloud.com/cos4/bucket
进入你的 bucket -> 基础配置 -> 跨域访问CORS设置

**Comment by wang1986573** [comment]
已经解决了，谢谢~~
