### ISSUE TITLE
后端签名时应当带上操作

### ISSUE THREAD

**Issue by untsop** [tencentyun/cos-js-sdk-v4#26]
否则无法限制签名的权限。例如我希望让用户在前台可以上传文件，但是不能列其他用户上传的文件，也不能删除文件。

按照目前的设计应该是无法实现这个限制的，这大大降低了 JS SDK 的安全性。

**Comment by untsop** [comment]
原来已经出了新的版本（V5），但是官方的文档还是链接到了旧版，我建议可以更新一下…

**Comment by carsonxu** [comment]
两个 SDK 都有在官网放链接，XML SDK 应该比较明显，贴一下你看到问题的文档？
