### ISSUE TITLE
多图片上传问题

### ISSUE THREAD

**Issue by yinxiaopeng** [tencentyun/cos-js-sdk-v4#28]
能上传多张图片吗？上传多张图片怎么将每张图片的进度分开，好像进度里面都不知道改进度是哪张图片的进度，那张图片成功了

**Comment by carsonxu** [comment]
cos.sliceUploadFile({
  Bucket: 'xxx',
  Region: 'xxx',
  TaskReady: function(TaskId){
     //这里记录下来对应关系
  }
})
TaskReady参数可以得到一个
