### ISSUE TITLE
getAppSign 与 getAppSignOnce 的问题

### ISSUE THREAD

**Issue by chengduxulei** [tencentyun/cos-js-sdk-v4#3]
我看源码中 uploadFile 方法只调用咯getAppSign  我们这里需求是想  一个签名对应一个文件 ，上传完之后签名失效。
1. 上传文件是否可用单次签名
2.  默认设置 getAppSign 一直报 APPID_USERID_NOTMATCH
 ![image](https://cloud.githubusercontent.com/assets/21352053/21832934/8f09c1ce-d7e9-11e6-97f7-80f166f02a5b.png)

**Comment by YinshawnRao** [comment]
可以单次
