### ISSUE TITLE
部分安卓手机uploadFile方法直接返回{"readyState":0,"responseText":"","status":0,"statusText":"error"}

### ISSUE THREAD

**Issue by warrior-bing** [tencentyun/cos-js-sdk-v4#30]
部分安卓手机uploadFile方法直接返回{"readyState":0,"responseText":"","status":0,"statusText":"error"}，
uploading... curr progress is NaN

**Comment by carsonxu** [comment]
如果是部分机型出现的错误，可以尝试配置 CORS AllowHeaders: *
如果还是不行，提供一下请求返回的 RequestId

**Comment by warrior-bing** [comment]
AllowHeaders已配置为*，目前只发现oppo r9跟锤子有问题，在successCallback返回的只有{"readyState":0,"responseText":"","status":0,"statusText":"error"}

**Comment by carsonxu** [comment]
返回的 header 里有个 x-cos-request-id 提供一下？

**Comment by warrior-bing** [comment]
{
 "code": -121,
 "message": "ERROR_CMD_CORSRULE_NOT_MATCH",
 "request_id": "NWE5M2ViODhfZDgyNzVkNjRfZDk1OF8yOTA5OTc="
}

**Comment by carsonxu** [comment]
ERROR_CMD_CORSRULE_NOT_MATCH 这个就是 CORS 配置有误
请检查请求参数是不是搞错了，导致请求到别的 bucket 去，然后检查你 bucket 的 CORS 是否正确。
如果还不行发一下你的 appid 和 bucket 看看

**Comment by warrior-bing** [comment]
这个是公用的方法，其他机型都能正常上传，只有oppo r9 跟锤子会报这个错误，bucket确认是正确的

**Comment by carsonxu** [comment]
一般这个表现是因为某些浏览器请求的时候会带有特定的 Access-Control-Request-Headers: origin,accept,content-type
你再次确认下 CORS 配置：AllowHeaders: *
如果还不行，请贴上 appid 和 bucket 我检查下

**Comment by warrior-bing** [comment]
抱歉，刚去检查了下配置，AllowHeaders没有配上导致的，耽误您时间了，实在抱歉，现在好了

**Comment by carsonxu** [comment]
ok
